# Generated by Django 2.1.2 on 2019-03-11 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0009_auto_20190312_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 12, 1, 2, 45, 225627)),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='appointment_time',
            field=models.TimeField(default=datetime.datetime(2019, 3, 12, 1, 2, 45, 225627)),
        ),
    ]
