# Generated by Django 2.1.2 on 2019-03-21 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0010_auto_20190312_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_for', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('sending_time', models.DateTimeField(default=datetime.datetime(2019, 3, 22, 5, 55, 43, 452900))),
                ('topic', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 22, 5, 55, 43, 451903)),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='appointment_time',
            field=models.TimeField(default=datetime.datetime(2019, 3, 22, 5, 55, 43, 451903)),
        ),
    ]
