# Generated by Django 2.1.2 on 2019-03-28 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0011_auto_20190322_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabletime',
            name='appointment_time',
        ),
        migrations.AddField(
            model_name='availabletime',
            name='available_in_afternoon',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=400),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='available_in_morning',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=400),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 28, 19, 42, 46, 452508)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 28, 19, 42, 46, 453504)),
        ),
    ]
