# Generated by Django 2.1.2 on 2019-04-21 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0012_auto_20190328_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='appointed_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='study_program.StudyProgram'),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 21, 20, 36, 5, 43951)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 21, 20, 36, 5, 44949)),
        ),
    ]
