# Generated by Django 2.1.2 on 2019-04-21 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0013_auto_20190421_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 22, 1, 0, 1, 388425)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 1, 0, 1, 389444)),
        ),
    ]
