# Generated by Django 2.1.2 on 2019-04-27 11:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0016_auto_20190422_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aun',
            name='assessment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='study_program.AssessmentResult'),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 27, 18, 21, 30, 231884)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 27, 18, 21, 30, 232881)),
        ),
    ]
