# Generated by Django 2.0.2 on 2019-05-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0017_auto_20190427_1821'),
        ('study_program', '0017_auto_20190422_1436'),
    ]

    operations = [
    ]
