# Generated by Django 2.1.2 on 2019-05-21 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0018_merge_20190521_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='pdf_docs_link',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='pdf_docs_link',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 22, 0, 12, 56, 538354)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 0, 12, 56, 539352)),
        ),
    ]
