# Generated by Django 2.1.2 on 2019-05-21 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0028_auto_20190522_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresult',
            name='pdf_docs',
            field=models.FileField(blank=True, upload_to='assessment_details/'),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 22, 2, 24, 50, 365722)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 2, 24, 50, 366719)),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='pdf_docs',
            field=models.FileField(blank=True, upload_to='study_program_details/'),
        ),
    ]
