# Generated by Django 2.1.2 on 2019-05-21 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0029_auto_20190522_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresult',
            name='curriculum_standard',
            field=models.IntegerField(choices=[(2550, 2550), (2551, 2551), (2552, 2552), (2553, 2553), (2554, 2554), (2555, 2555), (2556, 2556), (2557, 2557), (2558, 2558), (2559, 2559), (2560, 2560), (2561, 2561), (2562, 2562)], default=2019, verbose_name='มาตรฐานหลักสูตรตามปี'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='curriculum_status_year',
            field=models.IntegerField(choices=[(2550, 2550), (2551, 2551), (2552, 2552), (2553, 2553), (2554, 2554), (2555, 2555), (2556, 2556), (2557, 2557), (2558, 2558), (2559, 2559), (2560, 2560), (2561, 2561), (2562, 2562)], default=2019, verbose_name='หลักสูตรปี'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='year',
            field=models.IntegerField(choices=[(2550, 2550), (2551, 2551), (2552, 2552), (2553, 2553), (2554, 2554), (2555, 2555), (2556, 2556), (2557, 2557), (2558, 2558), (2559, 2559), (2560, 2560), (2561, 2561), (2562, 2562)], default=2019, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 22, 6, 30, 27, 284074)),
        ),
        migrations.AlterField(
            model_name='committee',
            name='year',
            field=models.IntegerField(choices=[(2550, 2550), (2551, 2551), (2552, 2552), (2553, 2553), (2554, 2554), (2555, 2555), (2556, 2556), (2557, 2557), (2558, 2558), (2559, 2559), (2560, 2560), (2561, 2561), (2562, 2562)], default=2019, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 6, 30, 27, 285071)),
        ),
        migrations.AlterField(
            model_name='professor',
            name='bsc_year',
            field=models.IntegerField(choices=[(2550, 2550), (2551, 2551), (2552, 2552), (2553, 2553), (2554, 2554), (2555, 2555), (2556, 2556), (2557, 2557), (2558, 2558), (2559, 2559), (2560, 2560), (2561, 2561), (2562, 2562)], default=2019, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='msc_year',
            field=models.IntegerField(choices=[(2550, 2550), (2551, 2551), (2552, 2552), (2553, 2553), (2554, 2554), (2555, 2555), (2556, 2556), (2557, 2557), (2558, 2558), (2559, 2559), (2560, 2560), (2561, 2561), (2562, 2562)], default=2019, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='phd_year',
            field=models.IntegerField(choices=[(2550, 2550), (2551, 2551), (2552, 2552), (2553, 2553), (2554, 2554), (2555, 2555), (2556, 2556), (2557, 2557), (2558, 2558), (2559, 2559), (2560, 2560), (2561, 2561), (2562, 2562)], default=2019, verbose_name='year'),
        ),
    ]
